### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Web\atomftp\misha\controladores'

### ISSUE THREAD

**Issue by puntoCL** [icetee/remote-ftp#1281] opened 2019-07-04 04:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\punto\Web\atomftp\misha\controladores'

```
At C:\Users\punto\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\punto\Web\atomftp\misha\controladores'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:530:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:368:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
  2x -9:46.1.0 editor:newline (input.hidden-input)
  2x -9:30.1.0 core:backspace (input.hidden-input)
     -9:26.5.0 core:move-right (input.hidden-input)
     -9:25.6.0 core:save (input.hidden-input)
     -8:35.8.0 core:paste (input.hidden-input)
     -8:35.3.0 core:save (input.hidden-input)
     -2:18.2.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -2:13.5.0 core:backspace (input.hidden-input)
     -2:10.5.0 core:confirm (input.hidden-input)
  2x -2:06.2.0 core:close (input.hidden-input)
     -1:59 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
  5x -1:56.8.0 core:backspace (input.hidden-input)
     -1:51.7.0 core:confirm (input.hidden-input)
     -1:42 remote-ftp:disconnect (li.directory.entry.list-nested-item.project-root.expanded.selected)
     -0:18.9.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.project-root.expanded.selected)
     -0:12.1.0 remote-ftp:disconnect (li.directory.entry.list-nested-item.project-root.expanded.selected)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-php 0.3.7 
file-icons 2.1.33 
highlight-selected 0.16.0 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment] 2019-12-23 02:54
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
