### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received false

### ISSUE THREAD

**Issue by benjonesqueens** [icetee/remote-ftp#882] opened 2017-07-05 21:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received false

```
At path.js:7

TypeError: Path must be a string. Received false
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:68:14)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:235:24)
    at /packages/remote-ftp/lib/connectors/ftp.js:263:17
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:16:14)
    at error (/packages/remote-ftp/lib/connectors/ftp.js:119:13)
    at /packages/remote-ftp/lib/connectors/ftp.js:141:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:513:11)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -5:31.1.0 remote-ftp:disconnect (li.file.entry.list-item.selected)
     -2:29.7.0 remote-ftp:add-folder (div.header.list-item)
     -2:26.9.0 core:confirm (input.hidden-input)
     -2:10.9.0 tree-view:add-folder (span.name.icon.icon-file-directory)
  5x -2:05.4.0 core:backspace (input.hidden-input)
     -1:58.7.0 core:confirm (input.hidden-input)
     -1:50.4.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
  2x -0:43 remote-ftp:upload-selected (span.name.icon.icon-file-directory)
     -0:13.4.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.3 
atom-html-preview 0.1.22 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.8 
highlight-selected 0.13.1 
hyperclick 0.1.1 
intentions 1.1.2 
linter 2.2.0 
linter-js-standard 3.9.1 
linter-php 1.3.2 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-pigments 0.2.2 
php-cs-fixer 4.1.0 
php-integrator-navigation 1.1.2 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
Remote-FTP 1.1.0 
wakatime 7.0.3 
```

**Comment by icetee** [comment] 2017-09-11 14:38
Duplicate of #535

**Closed as completed by icetee** 2017-09-11 14:38 UTC
