### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/AppData\Local\atom\app-1.29.0\storage\app\r...

### ISSUE THREAD

**Issue by 0n1dev** [icetee/remote-ftp#1209] opened 2018-09-14 01:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\all_m\AppData\Local\atom\app-1.29.0\storage\app\replay'

```
At C:\Users\all_m\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\all_m\AppData\Local\atom\app-1.29.0\storage\app\replay'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:674:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -0:47.6.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:24.8.0 remote-ftp:refresh-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.1.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.33.0 
color-picker 2.3.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.2 
remote-ftp 2.2.0 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:53 UTC
