### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir  while openning a file!

### ISSUE THREAD

**Issue by titan2420** [icetee/remote-ftp#1282] opened 2019-07-11 12:24 UTC
steps to reproduce:

1. created folder and file in remote server
2. clicked on file to open it, this error produced.

I checked the issue, I had a folder name in remote the same name as path in my local that was file!
Example:
- /var/www/deputation/app/controller/api/regulator/server(A Folder)
-/home/pwwiur/Desktop/Projects/deputation/app/controller/api/regulator/server (A File)

This error is happenning when syncing the folder from remote machine!

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/home/pwwiur/Desktop/Projects/deputation/app/controller/api/regulator/server/v1.0'

```
At /home/pwwiur/.atom/packages/remote-ftp/node_modules/mkdirp/index.js:90

Error: ENOTDIR: not a directory, mkdir '/home/pwwiur/Desktop/Projects/deputation/app/controller/api/regulator/server/v1.0'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:52 remote-ftp:delete-selected (span.name.icon.default-icon)
     -1:46.2.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -1:42.2.0 core:confirm (input.hidden-input)
     -1:07.7.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -1:05.0 core:backspace (input.hidden-input)
     -1:03.6.0 core:confirm (input.hidden-input)
     -0:38.6.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -0:34.6.0 core:confirm (input.hidden-input)
     -0:30.5.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -0:27.7.0 core:confirm (input.hidden-input)
     -0:23.3.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
  3x -0:21.2.0 core:backspace (input.hidden-input)
     -0:17.7.0 core:confirm (input.hidden-input)
     -0:10.7.0 intentions:highlight (input.hidden-input)
     -0:10.6.0 core:select-all (input.hidden-input)
     -0:10.2.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-icons 2.1.33 
hyperclick 0.1.5 
ide-php 0.7.18 
intentions 1.1.5 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.9.1 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment] 2019-12-23 03:03
Duplicate of #1054

**Closed as completed by icetee** 2019-12-23 03:03 UTC
