### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'F:/Projekte\Personal-Piloten\contao3.5\templa...

### ISSUE THREAD

**Issue by michaelgawlik** [icetee/remote-ftp#1178] opened 2018-06-05 08:51 UTC
[Enter steps to reproduce:]

1. want to open a file from the server for the first time
2. the file/path dosn't exist localy
3. cleared the local folder (maybe there was a hidden file or somthing)
4. after that it works fine

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: DESKTOP-9SS8SUC
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'F:\path\to\project'

```
At C:\Users\bla\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir F:\path\to\project'
    at fs.mkdirSync (fs.js:895:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:530:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:368:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:194:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
  2x -0:49.5.0 remote-ftp:disconnect (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
autoprefixer 3.7.1 
minimap 4.29.8 
monokai 0.24.0 
monokai-dark 1.5.0 
remote-ftp 2.2.0 
```

**Comment by icetee** [comment] 2019-12-23 02:52
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:52 UTC
