### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop/Programming/techsquad/htdocs/files ...

### ISSUE THREAD

**Issue by djpaul-dev** [icetee/remote-ftp#933] opened 2017-08-08 12:43 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/dhrubajyotipaul/Desktop/Programming/techsquad/htdocs/files for your website should be uploaded here!'

```
At /Users/dhrubajyotipaul/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/dhrubajyotipaul/Desktop/Programming/techsquad/htdocs/files for your website should be uploaded here!'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:250:26)
    at /packages/remote-ftp/lib/connectors/ftp.js:278:19
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:16:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:165:13
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:513:11)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
  2x -2:07.8.0 core:paste (input.hidden-input)
     -1:43.3.0 core:save (input.hidden-input)
     -1:32.5.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  7x -1:26.8.0 remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:16.9.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
remote-edit 1.9.0 
Remote-FTP 1.1.3 
remote-sync 4.1.5 
```

**Comment by icetee** [comment] 2017-08-17 14:21
Duplicate of #903

**Closed as completed by icetee** 2017-08-17 14:21 UTC
