### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\PhotoApp\app\views\categories'

### ISSUE THREAD

**Issue by nikzad-avasam** [icetee/remote-ftp#1218] opened 2018-10-31 20:00 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Sam\Desktop\PhotoApp\app\views\categories'

```
At C:\Users\Sam\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Sam\Desktop\PhotoApp\app\views\categories'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:797:12
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1084:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:25.9.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -1:22 core:confirm (input.hidden-input)
     -1:18.7.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
     -1:16.2.0 core:backspace (input.hidden-input)
     -1:14.1.0 core:confirm (input.hidden-input)
     -1:08.9.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.expanded.selected)
     -1:02.9.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -1:01.7.0 core:confirm (input.hidden-input)
     -0:48.9.0 remote-ftp:delete-selected (li.directory.entry.list-nested-item.expanded.selected)
     -0:35.9.0 remote-ftp:disconnect (atom-pane.pane)
     -0:27.3.0 remote-ftp:delete-selected (li.directory.entry.list-nested-item.expanded.selected)
     -0:22.6.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
  8x -0:19.8.0 core:backspace (input.hidden-input)
     -0:14.7.0 core:confirm (input.hidden-input)
     -0:10.4.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
     -0:07.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.26 
language-blade 0.41.4 
navigate 0.1.20 
platformio-ide-terminal 2.8.4 
remote-ftp 2.2.0 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:53 UTC
