### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'E:/蚁梦\Zero\template-parts\content'

### ISSUE THREAD

**Issue by yimmr** [icetee/remote-ftp#1268] opened 2019-04-25 07:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 ia32
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'E:\蚁梦\Zero\template-parts\content'

```
At C:\Users\Yim\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'E:\蚁梦\Zero\template-parts\content'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
```

### Commands

```
  2x -8:36.4.0 core:backspace (input.hidden-input)
  6x -8:22.6.0 core:move-left (input.hidden-input)
  6x -8:18.7.0 core:backspace (input.hidden-input)
     -8:09.9.0 core:save (input.hidden-input)
 24x -8:07.7.0 core:backspace (input.hidden-input)
  2x -6:12 core:save (input.hidden-input)
  3x -5:05.9.0 core:backspace (input.hidden-input)
  5x -4:49.9.0 core:move-left (input.hidden-input)
  7x -4:48.4.0 core:backspace (input.hidden-input)
     -4:21.9.0 editor:newline (input.hidden-input)
 11x -4:04.8.0 core:backspace (input.hidden-input)
     -3:31.9.0 core:move-right (input.hidden-input)
 14x -3:31.1.0 core:backspace (input.hidden-input)
     -2:47.7.0 editor:newline (input.hidden-input)
  5x -2:44.2.0 core:backspace (input.hidden-input)
     -2:37.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
remote-ftp 2.2.2 
simplified-chinese-menu 5.3.5 
teletype 0.13.3 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:53 UTC
