### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'Z:/Projects\dtthuy-ubuntu\.ftpconfig_google'

### ISSUE THREAD

**Issue by thanhacun** [icetee/remote-ftp#1055] opened 2017-11-13 01:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.3.1

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'Z:\Projects\dtthuy-ubuntu\.ftpconfig_google'

```
At fs.js:871

Error: ENOTDIR: not a directory, scandir 'Z:\Projects\dtthuy-ubuntu\.ftpconfig_google'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:576:28)
    at traverseTree (/packages/Remote-FTP/lib/helpers.js:135:27)
    at ConnectorSFTP.put (/packages/Remote-FTP/lib/connectors/sftp.js:460:9)
    at /packages/Remote-FTP/lib/client.js:658:26)
    at Client._next (/packages/Remote-FTP/lib/client.js:566:41)
    at /packages/Remote-FTP/lib/client.js:616:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:172:53)
    at /packages/Remote-FTP/lib/connectors/sftp.js:187:25
    at reread (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1575:16)
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -5:37.4.0 core:save (input.hidden-input)
     -4:43 intentions:highlight (input.hidden-input)
     -4:42.8.0 core:select-all (input.hidden-input)
     -4:42.3.0 intentions:highlight (input.hidden-input)
     -4:41.9.0 core:copy (input.hidden-input)
     -4:30.6.0 remote-ftp:create-ftp-config (ul.list-inline.tab-bar.inset-panel)
     -4:26.1.0 remote-ftp:create-sftp-config (ul.list-inline.tab-bar.inset-panel)
     -4:22.8.0 intentions:highlight (input.hidden-input)
     -4:22.4.0 core:select-all (input.hidden-input)
undefined -4:22 intentions:highlight (input.hidden-input)
     -4:16.6.0 core:paste (input.hidden-input)
     -4:09.2.0 intentions:highlight (input.hidden-input)
     -4:08.8.0 core:save (input.hidden-input)
     -3:59 remote-ftp:connect (ul.list-inline.tab-bar.inset-panel)
     -0:19.7.0 intentions:highlight (input.hidden-input)
     -0:19.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
busy-signal 1.4.3 
intentions 1.1.5 
js-refactor 0.7.5 
language-babel 2.78.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
refactor 0.11.5 
Remote-FTP 1.3.1 
sync-settings 0.8.3 
```

**Comment by icetee** [comment] 2017-11-13 09:34
Duplicate of #1054

**Closed as completed by icetee** 2017-11-13 09:34 UTC
