### ISSUE TITLE
Remote-FTP 1.1.3 Error

### ISSUE THREAD

**Issue by rqsakai** [icetee/remote-ftp#956] opened 2017-08-30 23:37 UTC
Atom keeps warning me to rebuild the remote ftp:

`binding@unknown – Cannot find module '/Users/sakai/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'`

**Comment by icetee** [comment] 2017-08-31 00:24
Thanks for report.
Duplicate of #839

**Closed as completed by icetee** 2017-08-31 00:24 UTC
