### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\jacky\home\ubuntu\openprovisioningt...

### ISSUE THREAD

**Issue by kwtsuiaa** [icetee/remote-ftp#1087] opened 2017-12-18 09:00 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\jackytsui\Desktop\jacky\home\ubuntu\openprovisioningtool\common\templates'

```
At C:\Users\jackytsui\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\jackytsui\Desktop\jacky\home\ubuntu\openprovisioningtool\common\templates'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:294:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

### Commands

```
     -2:06.7.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -2:02.8.0 core:confirm (input.hidden-input)
     -1:44.8.0 remote-ftp:delete-selected (span.name.icon.icon-file-directory)
     -1:36 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -1:33.7.0 core:confirm (input.hidden-input)
     -1:15.9.0 remote-ftp:delete-selected (span.name.icon.icon-file-directory)
     -1:12 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -1:09.7.0 core:confirm (input.hidden-input)
     -1:05.2.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:00.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-django 0.3.2 
autocomplete-python 1.10.3 
kite 0.58.0 
remote-ftp 2.1.2 
SFTP-deployment 1.0.2 
```

**Comment by icetee** [comment] 2017-12-18 11:48
Duplicate of https://github.com/icetee/remote-ftp/issues/903

**Closed as completed by icetee** 2017-12-18 11:48 UTC
