### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\s\var...

### ISSUE THREAD

**Issue by Dizic** [icetee/remote-ftp#1112] opened 2018-01-21 17:00 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Dizic\Desktop\s\var\www\html\admin\rcon\ssh'

```
At C:\Users\Dizic\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Dizic\Desktop\игры\OSPanel1\domains\wormax.io\var\www\html\admin\rcon\ssh'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.7.1 
busy-signal 1.4.3 
file-icons 2.1.15 
intentions 1.1.5 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.4 
linter-ui-default 1.6.10 
minimap 4.29.7 
php-integrator-base 3.1.0 
pigments 0.40.2 
project-manager 3.3.5 
remote-ftp 2.1.4 
teletype 0.5.0 
```

**Comment by icetee** [comment] 2018-05-15 16:49
Duplicate of #903

**Closed as completed by icetee** 2018-05-15 16:49 UTC
