### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '/Applications/XAMPP/xamppfiles/htdocs/nikukios...

### ISSUE THREAD

**Issue by digitak** [icetee/remote-ftp#1205] opened 2018-09-01 06:50 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Applications/XAMPP/xamppfiles/htdocs/nikukiosk/deployment-config.json'

```
At fs.js:904

Error: ENOTDIR: not a directory, scandir '/Applications/XAMPP/xamppfiles/htdocs/nikukiosk/deployment-config.json'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:580:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:137:27)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:741:24)
    at Client._next (/packages/remote-ftp/lib/client.js:643:39)
    at /packages/remote-ftp/lib/client.js:743:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:638:9)
    at /packages/remote-ftp/lib/connectors/ftp.js:665:16
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1084:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -2:32.5.0 core:cancel (input.hidden-input)
     -2:11.4.0 remote-ftp:toggle (div.header.list-item.project-root-header)
  2x -2:04.7.0 editor:newline (input.hidden-input)
     -2:02.1.0 core:paste (input.hidden-input)
     -1:58.3.0 core:copy (input.hidden-input)
     -1:54.8.0 core:cut (input.hidden-input)
     -1:54.5.0 core:save (input.hidden-input)
     -1:48.6.0 core:undo (input.hidden-input)
     -1:46.2.0 core:copy (input.hidden-input)
     -1:44.8.0 core:paste (input.hidden-input)
     -1:42.8.0 core:copy (input.hidden-input)
     -1:40.8.0 core:paste (input.hidden-input)
     -1:39.5.0 core:cut (input.hidden-input)
     -1:39.2.0 core:save (input.hidden-input)
  5x -1:36.2.0 remote-ftp:upload-selected (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
     -1:16.9.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
highlight-selected 0.14.0 
minimap 4.29.8 
remote-ftp 2.2.0 
```

**Comment by icetee** [comment] 2019-12-23 03:03
Duplicate of #1054

**Closed as completed by icetee** 2019-12-23 03:03 UTC
