### ISSUE TITLE
how to specify local path different than the current project path

### ISSUE THREAD

**Issue by chrisduong** [icetee/remote-ftp#387] opened 2016-05-27 09:51 UTC
Hi,

When I wanted to keep tracked of **remote files** within sub path of the current project, I don't see any configuration allow to do that.

Thanks for reading.

**Comment by christophevouillamoz** [comment] 2016-06-01 08:25
+1
Need it too

**Comment by isherwood** [comment] 2016-06-21 13:35
Same here. I'd like to have two different directory paths open on connect.

**Comment by jimmaaay** [comment] 2016-10-09 10:10
@chrisduong I'm not sure I understand fully, could you please clarify by what you mean?

**Comment by jimmaaay** [comment] 2016-10-09 10:29
Okay never mind I get it now. Duplicate of #361

**Closed as completed by jimmaaay** 2016-10-09 10:29 UTC
