### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '$ATOM_HOME/packages\remote-ftp\dashboard\incl...

### ISSUE THREAD

**Issue by guicuton** [icetee/remote-ftp#1273] opened 2019-05-27 22:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Funcouple\.atom\packages\remote-ftp\dashboard\includes\modules\bigdata'

```
At C:\Users\Funcouple\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Funcouple\.atom\packages\remote-ftp\dashboard\includes\modules\bigdata'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:77:24)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:797:12
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1084:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:59 core:copy (input.hidden-input)
  2x -1:58 core:paste (input.hidden-input)
     -1:49.7.0 core:save (input.hidden-input)
     -1:46.9.0 core:paste (input.hidden-input)
  2x -1:41.6.0 core:copy (input.hidden-input)
  2x -1:40.2.0 core:paste (input.hidden-input)
     -1:38.8.0 core:undo (input.hidden-input)
  2x -1:38 core:paste (input.hidden-input)
  2x -1:25.5.0 core:backspace (input.hidden-input)
     -1:24.4.0 core:save (input.hidden-input)
     -0:57.1.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -0:47.9.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
  5x -0:45.9.0 core:backspace (input.hidden-input)
     -0:42.3.0 core:confirm (input.hidden-input)
     -0:32.1.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
     -0:29.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
remote-ftp 2.2.2 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
