### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:/!Data\!Work\!remoteProjects\allomart\local...

### ISSUE THREAD

**Issue by igoralentyev** [icetee/remote-ftp#1280] opened 2019-06-26 11:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\!Data\!Work\!remoteProjects\allomart\local\components\main\mainpage.items.bestsellers\templates\main'

```
At C:\Users\igora\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\!Data\!Work\!remoteProjects\allomart\local\components\main\mainpage.items.bestsellers\templates\main'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:17.8.0 core:move-left (input.hidden-input)
  3x -1:17.5.0 core:backspace (input.hidden-input)
  2x -1:15.1.0 core:save (input.hidden-input)
     -1:13.2.0 find-and-replace:show (input.hidden-input)
     -1:13 core:paste (input.hidden-input)
     -1:12.7.0 core:confirm (input.hidden-input)
     -1:12.1.0 editor:consolidate-selections (input.hidden-input)
     -1:12.1.0 core:cancel (input.hidden-input)
  2x -1:10.2.0 core:move-left (input.hidden-input)
  3x -1:09.1.0 core:backspace (input.hidden-input)
     -1:06.7.0 core:move-left (input.hidden-input)
     -1:05.5.0 core:move-right (input.hidden-input)
     -1:05.2.0 core:save (input.hidden-input)
  2x -0:37.5.0 core:close (input.hidden-input)
     -0:19 core:select-all (input.hidden-input)
     -0:18.6.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
copy-path 0.5.1 
favorites 1.1.0 
minimap 4.29.9 
remote-ftp 2.2.2 
teletype 0.13.4 
tree-view-copy-relative-path 1.2.0 
```

**Comment by icetee** [comment] 2019-12-23 02:54
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
