### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by Bandeirex** [icetee/remote-ftp#978] opened 2017-09-26 14:09 UTC
[Enter steps to reproduce:]

1. ...Connect ftp
2. ...Download file

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'J:\Projects\Doctusware\error_log'

```
At C:\Users\utilizador\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'J:\Projects\Doctusware\error_log'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:250:26)
    at /packages/remote-ftp/lib/connectors/ftp.js:278:19
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:16:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:165:13
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:513:11)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -6:35.6.0 core:save (input.hidden-input)
     -5:42.1.0 intentions:highlight (input.hidden-input)
     -5:42 core:paste (input.hidden-input)
     -5:41.8.0 core:save (input.hidden-input)
     -3:24.5.0 docblockr:parse-tab (input.hidden-input)
     -3:24.5.0 snippets:next-tab-stop (input.hidden-input)
     -3:24.5.0 snippets:expand (input.hidden-input)
     -3:24.5.0 editor:indent (input.hidden-input)
     -3:23.9.0 docblockr:parse-tab (input.hidden-input)
     -3:23.9.0 snippets:next-tab-stop (input.hidden-input)
     -3:23.9.0 snippets:expand (input.hidden-input)
     -3:23.9.0 editor:indent (input.hidden-input)
     -3:23.4.0 intentions:highlight (input.hidden-input)
  2x -3:23.3.0 core:undo (input.hidden-input)
     -3:03.6.0 window:toggle-full-screen (ul.list-inline.tab-bar.inset-panel)
     -0:31.9.0 remote-ftp:delete-selected (span.name.icon.default-icon)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
angularjs 0.4.0 
artisan 0.3.1 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-ctags 5.1.0 
atom-ide-ui 0.4.0 
atom-material-syntax-dark 1.0.0 
atom-typescript 11.0.9 
autoclose-html 0.23.0 
autocomplete-corona 1.1.4 
autocomplete-modules 1.7.0 
autocomplete-paths 2.11.0 
blade-snippets 0.2.0 
busy-signal 1.4.3 
caniuse 0.9.2 
color-picker 2.2.5 
data-atom 0.25.2 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.12 
filesize 3.0.0 
flex-tool-bar 0.12.0 
flow-ide 1.8.1 
git-plus 7.9.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
Hydrogen 1.23.0 
hydrogen-launcher 1.2.1 
hyperclick 0.0.0 
ide-flowtype 0.17.4 
ide-php 0.6.8 
ide-typescript 0.6.1 
increment-selection 0.3.0 
intentions 1.1.5 
language-blade 0.36.0 
language-htaccess 0.1.1 
language-log 1.8.0 
language-lua 0.9.11 
language-puppet 0.23.0 
language-vue 0.23.1 
laravel 0.7.1 
less-than-slash 0.17.0 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-csslint 2.0.0 
linter-erb 1.1.0 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-lsc 2.4.0 
linter-luacheck 2.0.1 
linter-markdown 5.2.0 
linter-php 1.5.1 
linter-puppet-lint 0.8.3 
linter-sass-lint 1.8.0 
linter-scss-lint 3.1.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
livestyle-atom 0.2.10 
local-history 4.3.0 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
notifications-plus 0.69.8 
package-cop 0.2.10 
pdf-view 0.59.0 
php-getters-setters 0.5.5 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
quick-highlight 0.10.0 
regex-railroad-diagram 0.19.4 
Remote-FTP 1.1.3 
rest-client 1.3.1 
simple-drag-drop-text 0.3.4 
sort-lines 0.15.0 
split-diff 1.5.1 
swap-selection 0.4.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.3 
tab-control 0.6.10 
tasks 2.6.7 
todo-show 2.0.0 
toggle-quotes 1.0.1 
toggler 0.3.0 
tool-bar 1.1.0 
wordcount 2.10.4 
```

**Comment by icetee** [comment] 2017-09-28 19:25
Duplicate of #903

**Closed as completed** 2017-09-28 19:26 UTC
