### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'B:/Desktop_\Programmazione\site\Principale\ad...

### ISSUE THREAD

**Issue by Lettly** [icetee/remote-ftp#1049] opened 2017-11-05 18:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.3.1

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'B:\Desktop_\Programmazione\site\Principale\admints\moduli\crea'

```
At C:\Users\giuse\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'B:\Desktop_\Programmazione\site\Principale\admints\moduli\crea'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/platformio-ide/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:288:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:17.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -0:10.8.0 remote-ftp:delete-selected (span.name.icon.default-icon)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-css-clean 2.24.1 
atom-shell-commands 1.5.0 
autoclose-html 0.23.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-clang 0.11.4 
build 0.69.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-comb 2.5.0 
css-snippets 1.1.0 
file-icons 2.1.13 
html-tab 1.0.2 
html-to-css 0.2.2 
Hydrogen 2.0.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-batch 0.4.0 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-powershell 4.0.0 
language-unix-shell 0.40.1 
linter 2.2.0 
linter-gcc 0.7.1 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-bash-git 2.3.3 
Remote-FTP 1.3.1 
script 3.17.3 
scroll-through-time 0.2.0 
sync-settings 0.8.3 
toggler 0.3.0 
tool-bar 1.1.0 
w3c-validation 0.4.0 
webbox-color 0.5.9 
```

**Comment by icetee** [comment] 2017-12-18 11:48
Duplicate of https://github.com/icetee/remote-ftp/issues/903

**Closed as completed by icetee** 2017-12-18 11:48 UTC
