### ISSUE TITLE
Failed to activate the remote-ftp package

### ISSUE THREAD

**Issue by Dizic** [icetee/remote-ftp#1154] opened 2018-04-24 15:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Failed to activate the remote-ftp package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.26.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12204:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11548:33)
    at /packages/remote-ftp-master/lib/client.js:11:15)
    at /packages/remote-ftp-master/lib/client.js:1180:3)
    at Module.get_Module._compile (<embedded>:11588:36)
    at Object.value [as .js] (<embedded>:11840:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11548:33)
    at /packages/remote-ftp-master/lib/remote-ftp.js:13:15)
    at /packages/remote-ftp-master/lib/remote-ftp.js:249:3)
    at Module.get_Module._compile (<embedded>:11588:36)
    at Object.value [as .js] (<embedded>:11840:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (<embedded>:96:26)
    at Package.requireMainModule (<embedded>:73089:33)
    at Package.activateNow (<embedded>:72527:40)
    at measure (<embedded>:72513:33)
    at Package.measure (<embedded>:72395:25)
    at activationPromise.Promise (<embedded>:72507:20)
    at Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:72505:38)
    at PackageManager.activatePackage (<embedded>:25754:42)
    at config.transactAsync (<embedded>:25729:36)
    at Config.transactAsync (<embedded>:22350:28)
    at PackageManager.activatePackages (<embedded>:25727:23)
    at PackageManager.activate (<embedded>:25706:50)
    at loadStatePromise.loadState.then (<embedded>:1111:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
ide-php 0.7.14 
remote-ftp 2.1.4 
```

**Comment by icetee** [comment] 2018-05-14 23:31
Duplicate of #1104. Try re-install or move to folder in cmd and run this command: `apm install`.

**Closed as completed by icetee** 2018-05-14 23:31 UTC
