### ISSUE TITLE
After attempted update package uninstalled itself!

### ISSUE THREAD

**Issue by AlexNodex** [icetee/remote-ftp#1088] opened 2017-12-19 09:51 UTC
This is the error message I got!

```
Updating to “Remote-FTP@2.1.2” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/<myusername>/.atom/packages/remote-ftp/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by icetee** [comment] 2017-12-19 09:54
Please check already issues https://github.com/icetee/remote-ftp/issues/1084#issuecomment-352527103
Duplicate of #1084

**Closed as completed by icetee** 2017-12-19 09:54 UTC
