### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Desktop\Projekti\veljkoBlog\veljkoBlog\src\c...

### ISSUE THREAD

**Issue by veljko1992** [icetee/remote-ftp#1162] opened 2018-05-15 11:04 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\korisnik\Desktop\Projekti\veljkoBlog\veljkoBlog\src\components\showBlog.vue'

```
At fs.js:914

Error: ENOTDIR: not a directory, scandir 'C:\Users\korisnik\Desktop\Projekti\veljkoBlog\veljkoBlog\src\components\showBlog.vue'
    at Object.fs.readdirSync (fs.js:914:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:575:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:138:27)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:408:7)
    at /packages/remote-ftp/lib/client.js:717:24)
    at Client._next (/packages/remote-ftp/lib/client.js:625:39)
    at /packages/remote-ftp/lib/client.js:719:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:377:9)
    at /packages/remote-ftp/lib/connectors/ftp.js:404:16
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1078:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:194:7)
    at Parser._write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Parser.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -6:00.8.0 remote-ftp:create-ftp-config (div.tool-panel.tree-view)
  2x -5:37.7.0 core:paste (input.hidden-input)
     -4:52.4.0 remote-ftp:connect (input.hidden-input)
     -4:40.1.0 core:backspace (input.hidden-input)
     -4:33 remote-ftp:connect (input.hidden-input)
     -4:22.9.0 core:backspace (input.hidden-input)
     -4:18.9.0 core:redo (input.hidden-input)
     -4:17.6.0 core:undo (input.hidden-input)
     -4:17.1.0 core:redo (input.hidden-input)
  2x -4:16.6.0 core:undo (input.hidden-input)
  2x -4:10.3.0 core:backspace (input.hidden-input)
     -3:57.1.0 remote-ftp:connect (input.hidden-input)
     -3:40.8.0 application:add-project-folder (input.hidden-input)
     -2:20.5.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:58.7.0 remote-ftp:toggle (div.tool-panel.tree-view)
     -1:33.9.0 remote-ftp:upload-selected (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-beautify 0.32.3 
atom-html-preview 0.2.5 
atom-live-server 2.2.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.20 
language-vue 0.23.1 
minimap 4.29.8 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.8.1 
remote-ftp 2.1.4 
```

**Comment by icetee** [comment] 2018-05-15 16:47
Duplicate of #1054

**Closed as completed by icetee** 2018-05-15 16:47 UTC
