### ISSUE TITLE
Sync Local <- Remote for folder not working properly

### ISSUE THREAD

**Issue by mavalentin** [icetee/remote-ftp#984] opened 2017-09-28 18:55 UTC
If you sync a remote folder to local, it creates the contained folders of the remote folder in the root of the project, instead of syncing them in the proper location. 
The automatically created folders in the project root are all missing the first letter in their name, and they are empty.

**Comment by icetee** [comment] 2017-09-28 19:17
Duplicate of #918

**Closed as completed by icetee** 2017-09-28 19:17 UTC
