### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:/atom\ak\ak-ibw\public\iframe'

### ISSUE THREAD

**Issue by totoro1004** [icetee/remote-ftp#1312] opened 2019-12-01 03:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\atom\ak\ak-ibw\public\iframe'

```
At C:\Users\Administrator\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\atom\ak\ak-ibw\public\iframe'
    at mkdirSync (fs.js:731:3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:721:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:666:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Channel.Readable.push (_stream_readable.js:219:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:182:13)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SSH2Stream.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:666:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -2:43.9.0 application:reopen-project (atom-pane.pane.active)
     -2:16.5.0 remote-ftp:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:56.5.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
  2x -1:54.2.0 core:backspace (input.hidden-input)
     -1:52.1.0 core:confirm (input.hidden-input)
     -1:38.7.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.expanded.selected)
     -1:24.2.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -1:19.1.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -1:16.2.0 core:confirm (input.hidden-input)
     -1:12.2.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -1:07.9.0 core:confirm (input.hidden-input)
     -0:43.5.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.expanded.selected)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax-dark 1.0.0 
atom-python-run 0.9.7 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
browser-plus 0.0.98 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
git-plus 8.7.1 
highlight-selected 0.16.0 
intentions 1.1.5 
laravel 0.7.1 
linter 2.3.1 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
remote-ftp 2.2.2 
script 3.25.0 
seti-ui 1.11.0 
sync-settings 0.8.6 
```

**Comment by icetee** [comment] 2019-12-23 02:55
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:55 UTC
