### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '...'

### ISSUE THREAD

**Issue by gurupras** [icetee/remote-ftp#1159] opened 2018-05-09 15:36 UTC
### Steps to reproduce

1. Create a file on remote
2. Delete file
3. Create a directory with same name
4. Create a file under the directory

**Atom**: 1.26.1 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\Workspace\smartphones-exposed\dev\static\js'

```
At C:\Users\Guru\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'D:\Workspace\smartphones-exposed\dev\static\js'
    at fs.mkdirSync (fs.js:895:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SFTPStream.Writable.write (_stream_writable.js:241:11)
    at Channel.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Channel.Readable.push (_stream_readable.js:136:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SSH2Stream.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -5:23.7.0 autocomplete-plus:confirm (input.hidden-input)
  2x -5:22.8.0 core:delete (input.hidden-input)
  5x -5:22.1.0 core:move-up (input.hidden-input)
     -5:16.7.0 core:backspace (input.hidden-input)
     -5:14 intentions:highlight (input.hidden-input)
     -5:13.9.0 core:save (input.hidden-input)
     -0:41.7.0 remote-ftp:add-file (div.header.list-item)
     -0:39 core:confirm (input.hidden-input)
     -0:37.1.0 core:delete (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:35 remote-ftp:delete-selected (span.name.icon.default-icon)
     -0:32.1.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:31.5.0 core:confirm (input.hidden-input)
     -0:23.6.0 remote-ftp:add-file (span.name.icon.default-icon)
     -0:14.4.0 core:confirm (input.hidden-input)
     -0:11.6.0 intentions:highlight (input.hidden-input)
     -0:11.5.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-ide-ui 0.11.1 
atom-minify 0.8.0 
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.19 
go-debug 1.6.2 
go-plus 5.8.3 
go-signature-statusbar 1.2.3 
ide-typescript 0.7.6 
intentions 1.1.5 
language-ini 1.20.0 
language-pug 0.0.22 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-gcc 0.7.1 
linter-js-standard 5.0.0 
linter-ui-default 1.7.1 
motepair 0.24.0 
remote-ftp 2.1.4 
sync-settings 0.8.6 
teletype 0.13.2 
tool-bar 1.1.7 
```

**Comment by gurupras** [comment] 2018-05-09 15:44
OK. I figured out what the problem is and how to solve it. When you create a file on the remote and delete it, it only deletes it on the remote and not locally, which is the safe thing to do.

Unfortunately, now, when you try to create a _directory_ in the same name on remote, the package throws a confusing error rather than inform the user that there's a _file_ with the same name in local and thus it's unable to create a _directory_ with the same name in the remote as this would lead to inconsistencies.

Currently, the way to bypass this error is to delete the file locally and then try to create a directory.

**Comment by brianjcohen** [comment] 2018-05-09 16:38
I encountered this the other day as well and came to the same conclusions as you. I think the solution would be to make the error more clear.

**Comment by icetee** [comment] 2018-05-15 16:50
Duplicate of #903

**Closed as completed by icetee** 2018-05-15 16:50 UTC
