### ISSUE TITLE
Don't work sync

### ISSUE THREAD

**Issue by Obroten54** [icetee/remote-ftp#1056] opened 2017-11-13 13:30 UTC
Don't work sync.
![image](https://user-images.githubusercontent.com/23260905/32728039-e1109064-c88f-11e7-81ba-20dfe5c1b277.png)

Settings connection:
```
{
    "protocol": "sftp",
    "host": "217.182.***.***",
    "port": ******,
    "user": "***",
    "pass": "***************",
    "promptForPass": false,
    "remote": "/www/wp-content/",
    "local": "",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "remoteCommand": "",
    "remoteShell": "",
    "watch": [],
    "watchTimeout": 500
}
```

OS: Linux Ubuntu 16.04
Ver. Athom: 1.20.1 (x64)
Ver. Package: 1.3.1

**Comment by icetee** [comment] 2017-11-13 15:33
Duplicate of #1016

**Closed as completed by icetee** 2017-11-13 15:33 UTC
