### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '/Applications/AMPPS/www/evoluzionz.com/inside...

### ISSUE THREAD

**Issue by sakorada** [icetee/remote-ftp#1263] opened 2019-04-13 06:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Applications/AMPPS/www/evoluzionz.com/insider/edit'

```
At /Users/user/.atom/packages/remote-ftp/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Applications/AMPPS/www/evoluzionz.com/insider/edit'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:797:12
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1084:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -0:56.9.0 remote-ftp:connect (input.hidden-input)
     -0:38.8.0 tree-view:add-folder (div.header.list-item)
     -0:28.5.0 remote-ftp:delete-selected (li.directory.entry.list-nested-item.expanded.selected)
     -0:19.3.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -0:14.8.0 core:confirm (input.hidden-input)
     -0:09.5.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -0:05.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ajax-request 0.1.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-bootstrap4 1.4.0 
atom-live-server 2.3.0 
autocomplete-clang 0.11.5 
browser-plus 0.0.98 
browser-refresh-on-save 1.0.0 
build 0.70.0 
busy-signal 2.0.1 
color-picker 2.3.0 
file-icons 2.1.31 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-arduino 0.4.3 
language-chordpro 0.2.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-php 1.6.0 
linter-ui-default 1.7.1 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide 2.2.6 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
remote-ftp 2.2.2 
rest-client 1.3.1 
rester 1.1.1 
tool-bar 1.1.11 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:53 UTC
