### ISSUE TITLE
Installing “Remote-FTP@2.1.1” failed

### ISSUE THREAD

**Issue by pagestyles** [icetee/remote-ftp#1082] opened 2017-12-13 10:23 UTC
Remote-FTP install fails every time i try to install it.
MacOS High Sierra 10.13.1

```
Installing “Remote-FTP@2.1.1” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/[REMOVED]/.atom/packages/Remote-FTP/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by icetee** [comment] 2017-12-13 10:29
Duplicate of https://github.com/icetee/remote-ftp/issues/1066

**Closed as completed by icetee** 2017-12-13 10:29 UTC
