### ISSUE TITLE
Rewrite remote changes from Atom

### ISSUE THREAD

**Issue by fargoss** [icetee/remote-ftp#753] opened 2017-04-03 14:52 UTC
I notice a problem: 

If open the file in Atom from a remote server and making changes at same time on the file on a remote server (for example: ssh), Atom doesn't check changes. While saving the file from the Atom, it rewrite changes make on a remote server, don't warning about this.

**Comment by fargoss** [comment] 2017-04-03 14:58
1. open file in Atom
2. make changes in the file on ssh (git pull)
3. Atom doesn't check new file version and i can rewrite remoting changes!

**Comment by ryanpcmcquen** [comment] 2017-04-18 00:01
I am also being bit by this. Is there any way to implement this kind of functionality?

**Comment by ryanpcmcquen** [comment] 2017-04-18 00:06
Looks like this is a duplicate of https://github.com/mgrenier/remote-ftp/issues/132.

**Closed as completed** 2017-06-17 02:36 UTC
Labels: duplicate
