### ISSUE TITLE
Show error if file upload fails

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#394] opened 2016-06-05 15:58 UTC
It would be really nice to know that on save, the file upload wasn't successful. 

For instance,

**Scenario**
The user doesn't have write permissions to a particular file but has read permissions. The user edits the file and saves it using `remote-ftp`!

**What happens?**
File upload fails, no error message is prompted. The file saves locally without any issues. 

On refresh and re-download (from the right-click menu on the _file_ from the tree) : The file returns to its original state, changes made via `remote-ftp` are lost.

**What should happen?**
Prompt the user with error message like : 
`File upload failed. 
 Open for write : Permission denied`

**Comment by jimmaaay** [comment] 2016-10-09 10:06
Duplicate of #111

**Closed as completed by jimmaaay** 2016-10-09 10:06 UTC
Labels: enhancement
