### ISSUE TITLE
Sync local -> remote ignores deleted folders

### ISSUE THREAD

**Issue by fugamma** [icetee/remote-ftp#791] opened 2017-05-12 19:25 UTC
If I remove a folder from the local server and attempt to use Sync local -> remote, the folder will not be removed on the remote server. 

If I sync conversely, then the folder will be added back to the local server.

**Comment by icetee** [comment] 2017-09-28 21:20
Duplicate of #791

**Closed as completed by icetee** 2017-09-28 21:20 UTC
