### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '/Volumes/TRABALHOS/TRABALHOS/Tem Defeito/SIST...

### ISSUE THREAD

**Issue by pedroleao87** [icetee/remote-ftp#1291] opened 2019-08-21 00:08 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Volumes/TRABALHOS/TRABALHOS/Tem Defeito/SISTEMA/luiz/public_html/application/views/administrador'

```
At /Users/rickleao/.atom/packages/remote-ftp/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Volumes/TRABALHOS/TRABALHOS/Tem Defeito/SISTEMA/luiz/public_html/application/views/administrador'
    at Object.fs.mkdirSync (fs.js:872:3)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:530:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:368:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:187:15)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -0:17 remote-ftp:toggle (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment] 2019-12-23 02:54
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
