### ISSUE TITLE
Feature request: multiple ftp configuration for one project

### ISSUE THREAD

**Issue by matteo-tonini** [icetee/remote-ftp#400] opened 2016-06-10 09:48 UTC
I usually work with DEV and LIVE server, so for a single project, would be great to have the possibility to specify multiple ftp configurations in the .ftpconfig and then switch easily between them using shortcuts/menu.

**Comment by hatzopoulos** [comment] 2016-06-11 17:22
Duplicate of https://github.com/mgrenier/remote-ftp/issues/44

**Closed as completed** 2016-08-15 21:35 UTC
