### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/OneDrive\문서\phpProject\project\user'

### ISSUE THREAD

**Issue by kwon0822** [icetee/remote-ftp#1311] opened 2019-11-19 08:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\kwon0\OneDrive\문서\phpProject\project\user'

```
At C:\Users\kwon0\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\kwon0\OneDrive\문서\phpProject\project\user'
    at mkdirSync (fs.js:731:3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:721:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:530:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:368:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:187:15)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -0:08.8.0 remote-ftp:sync-with-remote (li.directory.entry.list-nested-item.project-root.expanded.selected)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
code-peek 1.4.21 
color-picker 2.3.0 
emmet 2.4.3 
highlight-line 0.12.0 
highlight-selected 0.16.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
remote-ftp 2.2.2 
seti-icons 1.5.4 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
swackets 0.35.0 
```

**Comment by icetee** [comment] 2019-12-23 02:55
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:55 UTC
