### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by sparket42** [icetee/remote-ftp#983] opened 2017-09-28 18:42 UTC
remote-ftp 1.1.4
atom 1.20.1
MacOS 10.13
 Atom tell me "Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."
I tried to rebuild packages but get this error:

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-electron-v1.6-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and electron@1.6.9 (electron-v1.6 ABI) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "clean"
gyp ERR! cwd /Users/wuyu/.atom/packages/remote-ftp/node_modules/fsevents
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/wuyu/.atom/packages/remote-ftp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 17.0.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/wuyu/.atom/packages/remote-ftp/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/wuyu/.atom/packages/remote-ftp/node_modules/fsevents
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 

npm ERR! Darwin 17.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/wuyu/.atom/.apm/.apmrc" "--userconfig" "/Users/wuyu/.atom/.apmrc" "rebuild" "--runtime=electron" "--target=1.6.9" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.1.2 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.1.2 install script 'node install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wuyu/.atom/packages/remote-ftp/npm-debug.log

**Comment by icetee** [comment] 2017-09-28 19:02
Duplicate of https://github.com/icetee/remote-ftp/issues/839#issuecomment-313857979

**Closed as completed by icetee** 2017-09-28 19:02 UTC
