### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/AppData\Local\atom\app-1.38.1\htdocs\java'

### ISSUE THREAD

**Issue by berktuna991** [icetee/remote-ftp#1278] opened 2019-06-17 10:59 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Berk Tuna\AppData\Local\atom\app-1.38.1\htdocs\java'

```
At C:\Users\Berk Tuna\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Berk Tuna\AppData\Local\atom\app-1.38.1\htdocs\java'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:797:12
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1084:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:18.8.0 core:backspace (input.hidden-input)
     -1:18.1.0 autocomplete-plus:confirm (input.hidden-input)
     -1:18.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:11.2.0 core:move-right (input.hidden-input)
  8x -1:10 core:move-left (input.hidden-input)
  7x -1:07.0 core:move-right (input.hidden-input)
  6x -1:05.2.0 core:backspace (input.hidden-input)
     -1:02.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:38.9.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
 13x -0:35.5.0 core:backspace (input.hidden-input)
     -0:31.4.0 core:confirm (input.hidden-input)
     -0:25.4.0 remote-ftp:delete-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.2.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -0:20.3.0 core:confirm (input.hidden-input)
     -0:16.2.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
     -0:13.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
remote-ftp 2.2.2 
teletype 0.13.4 
```

**Comment by icetee** [comment] 2019-12-23 02:54
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
