### ISSUE TITLE
Transfer connection mode

### ISSUE THREAD

**Issue by lenguyenitc** [icetee/remote-ftp#702] opened 2017-02-21 09:34 UTC
Hi,
I love your package. It so helpfully.
I have a question.
How to change transfer connection mode(ex: active or passtive)?
I connected with transfer mode default but file not listing.
Hope you can help.
Thank in advance!

**Comment by samifouad** [comment] 2017-02-21 13:45
There's only support for passive mode.

Some other FTP clients offer active as an option, but typically use passive by default. This Atom package relies on a nodejs plugin which only offers passive support, but there is good reason to not support active mode due to how it's designed. 

It's a lengthy technical topic and there's a lot of research/articles available via Google, but essentially you should configure your FTP server for passive and if you are at a hosting company, ask them to change it.

**Comment by hatzopoulos** [comment] 2017-02-21 17:38
Closing. Also duplicate of https://github.com/mgrenier/remote-ftp/issues/188

**Closed as completed by hatzopoulos** 2017-02-21 17:38 UTC
