### ISSUE TITLE
No longer works. Installed today.

### ISSUE THREAD

**Issue by timothymarois** [icetee/remote-ftp#907] opened 2017-07-17 21:58 UTC
Installed it today (I have used it in the past) however today nothing works, seemed to take quite a while to initially install. The toggle, connect etc do not open up the side bar. So far for me its completely broken. Let me know what else I need to provide.

**Comment by eristoddle** [comment] 2017-07-18 01:12
Seems to be the same for me.

**Comment by icetee** [comment] 2017-07-18 07:07
Is this a problem? #839

**Comment by RebelDesign** [comment] 2017-07-18 16:57
Went to go for the update as it was a few days old - guess I jumped in too soon. 

The toggle function seems to not work at all. 
Even tried "apm rebuild" with no success. 


Edit - Found a working solution. Hopefully this will work for others as well. 

cd ~/.atom/packages/Remote-ftp
npm install
apm install
Restart Atom. 
Now working.

**Comment by sangdth** [comment] 2017-07-21 10:06
@RebelDesign I've tried. Not working for me.

**Comment by EvanHerman** [comment] 2017-07-21 14:14
@RebelDesign I have also tried the above steps, but that didn't resolve it for me.

**Comment by EvanHerman** [comment] 2017-07-21 14:26
@sangdth I've come across a fix - found at the bottom of https://github.com/icetee/remote-ftp/issues/839

In short, from within Atom open up the packages manager using `Shift-Command-P` and type `Incompatible Packages`.

On that page you should see a few errors regarding Remote-FTP. At the top right of the page click on 'Rebuild Packages' - and the packages will be rebuilt. Once completed, restart Atom and things should be working again.

👍

**Comment by RebelDesign** [comment] 2017-07-21 16:30
@ sangdth
@EvanHerman 
Hopefully future people will find this helpful for a while...
----

Incompatible Packages was something that I tried without luck. 

CLI command: apm rebuild basically did the same task - Try this command or even better....
Try this one - apm rebuild-module-cache

My main issue was solved by having them built or rebuilt....I just tried everything I found until it worked.

**Comment by timothymarois** [comment] 2017-07-21 17:06
@icetee Yes i believe its the same issue. Though I dont know for sure. I'm installing it once more today, and when I click install, it literally just sits there just saying that its installing. Doesn't look like anything is happening almost as its frozen up. Options appear, but when you click toggle sidebar, it does nothing, and connect also does nothing.

**Comment by icetee** [comment] 2017-07-21 18:04
[Chokidar](https://github.com/paulmillr/chokidar) plugin installed for macOS. They are quicker to watch files. I came to somehow incompatible with installation / updates.

It is likely to be related to this. [Chokidar issue](https://github.com/paulmillr/chokidar/issues/618). There will be a problem.

Did not that solve it then? https://github.com/icetee/remote-ftp/issues/839#issuecomment-313811278

**Comment by icetee** [comment] 2017-08-17 23:27
Duplicate of #839

**Closed as completed by icetee** 2017-08-17 23:27 UTC
