### ISSUE TITLE
Uncaught TypeError: Cannot read property 'host' of null

### ISSUE THREAD

**Issue by vsosp16** [icetee/remote-ftp#1033] opened 2017-10-25 16:59 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'host' of null

```
At C:\Users\vsosp\.atom\packages\Remote-FTP\lib\client.js:150

TypeError: Cannot read property 'host' of null
    at Client.setProjectName (/packages/Remote-FTP/lib/client.js:150:27)
    at /packages/Remote-FTP/lib/client.js:138:16
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:248:20)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at HTMLSelectElement.changeHandler (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-panel.js:251:24)
```

### Commands

```
     -5:59.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -5:21.9.0 core:paste (div.placeholder-text)
     -5:16.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
change-case 0.6.5 
emmet 2.4.3 
file-icons 2.1.13 
jshint 1.8.6 
Remote-FTP 1.2.6 
```

**Comment by icetee** [comment] 2017-10-25 17:01
Duplicate of #1029

**Closed as completed by icetee** 2017-10-25 17:01 UTC
