### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '$ATOM_HOME/packages\remote-ftp\lib\connectors...

### ISSUE THREAD

**Issue by lifeunsubscribe** [icetee/remote-ftp#1298] opened 2019-09-13 18:41 UTC
[Enter steps to reproduce:]

1. tried to make a folder with a name, but accidentally made a file instead
2. promptly deleted file and tried to make folder instead
3.tried to create file inside this folder
4. remote does not like this for some reason, and cites the name of my folder already being used on a file (even though I deleted that file and I wasn't reusing its name)

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Sarahhh\.atom\packages\remote-ftp\lib\connectors\BobsCOP\wadley_sarah_p1'

```
At C:\Users\Sarahhh\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Sarahhh\.atom\packages\remote-ftp\lib\connectors\BobsCOP\wadley_sarah_p1'
    at fs.mkdirSync (fs.js:872:3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:727:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:672:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Channel.Readable.push (_stream_readable.js:219:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:182:13)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SSH2Stream.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:672:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -0:47.6.0 remote-ftp:sync-with-remote (li.directory.entry.list-nested-item.project-root.expanded.selected)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment] 2019-12-23 02:54
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
