### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '/\dc3\user$\slevkov\blog\mail\20171228'

### ISSUE THREAD

**Issue by Mezzzanine** [icetee/remote-ftp#1095] opened 2017-12-29 06:56 UTC
[Enter steps to reproduce:]

1. Connect to FTP
2. Trying to sync remote -> local (local folder is in the network \\dc3\user$\***)
3.Error

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: �������� Windows 10 Pro (Registered Trademark)
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.2

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '\\dc3\user$\slevkov\blog\mail\20171228'

```
At fs.js:871

Error: ENOTDIR: not a directory, scandir '\\dc3\user$\slevkov\blog\mail\20171228'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:576:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:138:27)
    at /packages/remote-ftp/lib/client.js:795:9
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at error (/packages/remote-ftp/lib/connectors/ftp.js:116:29)
    at /packages/remote-ftp/lib/connectors/ftp.js:139:29
    at final (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:507:11)
    at Object.cb (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:544:11)
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -0:16.8.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
close-tags 0.6.0 
minimap 4.29.7 
open-in-browser 0.5.2 
language-twig 1.6.3 
quick-highlight 0.12.0 
remote-ftp 2.1.2 
twilight-syntax 0.8.0 
```

**Comment by icetee** [comment] 2018-05-15 16:47
Duplicate of #1054

**Closed as completed by icetee** 2018-05-15 16:47 UTC
