### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:/Sites\RubyRealmsAdmin\www\html\main\contro...

### ISSUE THREAD

**Issue by robert-cooper-developer** [icetee/remote-ftp#1240] opened 2018-12-24 03:57 UTC
[Enter steps to reproduce:]

1. Create a file with no file type extension (such as .php)
2. Delete file
3. Create folder named the exact same thing
4. Create file in folder
5. Attempt to download file from folder via FTP

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Sites\RubyRealmsAdmin\www\html\main\controllers\moderation'

```
At C:\Users\Aeri-2.0\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Sites\RubyRealmsAdmin\www\html\main\controllers\moderation'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
```

### Commands

```
     -0:16.3.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -0:13.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
gpp-compiler 3.0.7 
php-twig 4.0.0 
remote-ftp 2.2.2 
teletype 0.13.3 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:53 UTC
