### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\ftpconfig\yapi\arac'

### ISSUE THREAD

**Issue by create07** [icetee/remote-ftp#1027] opened 2017-10-23 01:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.6

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Create\Desktop\ftpconfig\yapi\arac'

```
At C:\Users\Create\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Create\Desktop\ftpconfig\yapi\arac'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/Remote-FTP/lib/connectors/ftp.js:208:8)
    at /packages/Remote-FTP/lib/connectors/ftp.js:357:14
    at /packages/Remote-FTP/lib/connectors/ftp.js:199:9
    at Object.cb (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:373:5)
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
```

### Non-Core Packages

```
Remote-FTP 1.2.6 
```

**Comment by icetee** [comment] 2017-10-23 10:30
Duplicate of #903

**Closed as completed by icetee** 2017-10-23 10:30 UTC
