### ISSUE TITLE
Wanting to use two or even three different sftp tabs/windows

### ISSUE THREAD

**Issue by RebelDesign** [icetee/remote-ftp#678] opened 2017-02-02 22:57 UTC
I have a very hard time switching between production server and staging servers. Currently, I have duplicated the .ftpconfig file, using naming conventions like .ftpconfig-1, .ftpconfig-2, .ftpconfig-3....etc. I just duplicate the .ftpconfig-1 and then rename it to .ftpconfig and connect. It would be really awesome if there was a memory of accounts or even a easy way to switch between the two.

Secondly, using a drag and drop feature would be really amazing. I open need to move files from one file to another and dont want to have to use the command line to move the files.

Really - REALLY love the addon to atom - Keep up the good work!

**Comment by mstearne** [comment] 2017-02-02 23:03
Rebel,

To manage multiple servers, create on your local machine for each server that has a separate .ftpconfig in each.

For example

www-dev/
 .ftpconfig - with ftp settings for development

www-prod/
 .ftpconfig - with ftp settings for production

In Atom go to File…Open… and open www-dev then go to File…Open… and open www-prod giving you two Atom windows. In each window go to Packages -> Remote-FTP -> Toggle where you’ll see the Connect button.


Michael

**Comment by samifouad** [comment] 2017-02-03 14:01
Looking at the source code, multiple servers seems like something that may come some time in the future, but for now the multiple window method Michael suggested is a good workflow.

And I agree that dragging and dropping within the treeview is a good feature to have. It may be some time before that's added. If you're really interested in it, I'd encourage you to hack away and add the feature and contribute it back to this code repo as a pull request!

**Comment by samifouad** [comment] 2017-02-22 05:50
I'm going to close this as a duplicate of #44

**Closed as completed by samifouad** 2017-02-22 05:50 UTC
