### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\trato\trato'

### ISSUE THREAD

**Issue by mustroph** [icetee/remote-ftp#958] opened 2017-09-05 09:43 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\MSI\Desktop\trato\trato'

```
At C:\Users\MSI\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\MSI\Desktop\trato\trato'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:190:20
    at /packages/remote-ftp/lib/connectors/ftp.js:222:20
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -5:47.4.0 intentions:highlight (input.hidden-input)
     -5:47.2.0 core:copy (input.hidden-input)
     -5:46.5.0 intentions:highlight (input.hidden-input)
     -5:46.4.0 core:paste (input.hidden-input)
     -5:44.9.0 intentions:highlight (input.hidden-input)
     -5:44.8.0 core:paste (input.hidden-input)
     -5:42.9.0 core:backspace (input.hidden-input)
     -3:51.6.0 intentions:highlight (input.hidden-input)
     -3:51.4.0 core:save (input.hidden-input)
     -3:08.5.0 intentions:highlight (input.hidden-input)
     -3:08.2.0 find-and-replace:select-next (input.hidden-input)
     -2:39.8.0 intentions:highlight (input.hidden-input)
  5x -2:39.4.0 find-and-replace:select-next (input.hidden-input)
     -2:35 intentions:highlight (input.hidden-input)
  6x -2:34.9.0 find-and-replace:select-next (input.hidden-input)
  2x -0:27.1.0 remote-ftp:disconnect (ol.entries.list-tree)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.8 
Remote-FTP 1.1.3 
sass-autocompile 0.13.3 
```

**Comment by icetee** [comment] 2017-09-28 19:25
Duplicate of #903

**Closed as completed by icetee** 2017-09-28 19:25 UTC
