### ISSUE TITLE
Warn more conspicuously when file isn't saved

### ISSUE THREAD

**Issue by isherwood** [icetee/remote-ftp#409] opened 2016-06-21 13:39 UTC
I've wasted some time debugging only to discover that my changes haven't been saved. There's no indication when a connection isn't present other than the Uploading status. If I forget to watch it I don't realize that the connection has been lost. 

Thank you.

**Comment by jimmaaay** [comment] 2016-10-09 10:06
Duplicate of #111

**Closed as completed by jimmaaay** 2016-10-09 10:06 UTC
Labels: enhancement
