### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/SNO /scratch/SNOp/Studies/k40'

### ISSUE THREAD

**Issue by WaqarSM** [icetee/remote-ftp#1308] opened 2019-11-06 15:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/mwaqar/SNO /scratch/SNOp/Studies/k40'

```
At /Users/mwaqar/.atom/packages/remote-ftp/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/mwaqar/SNO /scratch/SNOp/Studies/k40'
    at Object.mkdirSync (fs.js:731:3)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:666:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Channel.Readable.push (_stream_readable.js:219:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:182:13)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SSH2Stream.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:666:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -0:34.1.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -0:25.6.0 core:confirm (input.hidden-input)
     -0:08.8.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-bracket-highlight 0.3.2 
busy-signal 1.4.3 
color-picker 2.3.0 
flatwhite-syntax 0.8.1 
highlight-selected 0.14.0 
intentions 1.1.5 
kary-foundation-light 4.0.0 
language-latex 1.2.0 
language-matlab 0.2.1 
language-root 1.0.2 
latex 0.50.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
nms-color-bracket 0.1.0 
pdf-view 0.71.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
print-atom 0.1.1 
remote-edit 1.9.0 
remote-ftp 2.2.2 
script 3.18.1 
split-diff 1.5.3 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by icetee** [comment] 2019-12-23 02:54
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:54 UTC
