### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'C:/xampp\htdocs\ADMINBARU\application\views\ta...

### ISSUE THREAD

**Issue by cnjonathan** [icetee/remote-ftp#1179] opened 2018-06-06 15:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\xampp\htdocs\ADMINBARU\application\views\tampil\verifikasi\verifikasi_v.php'

```
At fs.js:914

Error: ENOTDIR: not a directory, scandir 'C:\xampp\htdocs\ADMINBARU\application\views\tampil\verifikasi\verifikasi_v.php'
    at Object.fs.readdirSync (fs.js:914:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:575:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:137:27)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:741:24)
    at Client._next (/packages/remote-ftp/lib/client.js:643:39)
    at /packages/remote-ftp/lib/client.js:689:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:153:9
    at final (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:502:11)
    at Socket.ondone (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:477:7)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -0:38.8.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.project-root.expanded.selected)
     -0:29.9.0 remote-ftp:upload-selected (span.name.icon.icon-repo)
     -0:29.9.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:24.9.0 remote-ftp:upload-selected (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
file-icons 2.1.15 
highlight-selected 0.13.1 
platformio-ide-terminal 2.8.0 
remote-ftp 2.2.0 
```

**Comment by icetee** [comment] 2019-12-23 03:02
Duplicate of #1054

**Closed as completed by icetee** 2019-12-23 03:02 UTC
