### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'D:/workspace\ci\views\js'

### ISSUE THREAD

**Issue by gigi2444** [icetee/remote-ftp#1138] opened 2018-03-12 07:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\workspace\ci\views\js'

```
At C:\Users\Truffel\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'D:\workspace\ci\views\js'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:358:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:373:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:04.7.0 core:move-left (input.hidden-input)
  8x -1:04.5.0 core:move-up (input.hidden-input)
  2x -1:04.0 core:move-right (input.hidden-input)
     -1:03.5.0 core:move-down (input.hidden-input)
 15x -1:03.3.0 core:move-right (input.hidden-input)
     -1:02.4.0 core:move-down (input.hidden-input)
 67x -1:02.2.0 core:move-right (input.hidden-input)
     -0:44.1.0 core:select-all (input.hidden-input)
     -0:43.6.0 core:copy (input.hidden-input)
     -0:36.9.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:35.8.0 core:confirm (input.hidden-input)
     -0:30.9.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:28.7.0 core:confirm (input.hidden-input)
     -0:21.9.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:20.1.0 core:confirm (input.hidden-input)
     -0:10.6.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
autocomplete-python 1.10.5 
beautify 0.31.0 
docblockr 0.13.7 
emmet 2.4.3 
Hydrogen 2.2.3 
minimap 4.29.8 
python-snippets 1.9.0 
remote-ftp 2.1.4 
```

**Comment by icetee** [comment] 2018-05-15 16:49
Duplicate of #903

**Closed as completed by icetee** 2018-05-15 16:49 UTC
