### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/####/.atom/packages/Remote-FTP/package.json'

### ISSUE THREAD

**Issue by ranggaperwiratama** [icetee/remote-ftp#1065] opened 2017-11-27 04:58 UTC
Installing “Remote-FTP@2.0.0” failed.Hide output…
(node:4171) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/###/.atom/packages/Remote-FTP/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at Proxy.fs.readFileSync (fs.js:568:33)
    at Proxy.fs.readFileSync (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:86:27)
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:476:42
    at fn (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by cyberwebstuff** [comment] 2017-11-28 11:37
Same problem here :-(

**Comment by icetee** [comment] 2017-11-28 19:44
Duplicate of #1066

**Closed as completed by icetee** 2017-11-28 19:44 UTC
