### ISSUE TITLE
remote file  are treated as folders

### ISSUE THREAD

**Issue by seanchann** [icetee/remote-ftp#518] opened 2016-10-28 09:10 UTC
Hi:
   atom: 1.12.0-beta5
   remote-ftp: 0.9.0
   local os : win10
   remote os: centos7
   protocol: sftp

   I connect to remote. the remote file always as a folder in tree view. 
   and   can't sync from remote to local

**Comment by jimmaaay** [comment] 2016-10-28 12:31
Duplicate of #501

**Closed as completed by jimmaaay** 2016-10-28 12:31 UTC
