### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/SkyDrive\Documents\ocms\templates\resources'

### ISSUE THREAD

**Issue by sayanarijit** [icetee/remote-ftp#985] opened 2017-09-29 11:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Single Language
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\subhajit\SkyDrive\Documents\ocms\templates\resources'

```
At C:\Users\subhajit\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\subhajit\SkyDrive\Documents\ocms\templates\resources'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:254:14
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3443:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -8:19.4.0 editor:toggle-line-comments (input.hidden-input)
  2x -7:21.4.0 core:save (input.hidden-input)
  2x -3:53 core:backspace (input.hidden-input)
     -3:49.9.0 core:undo (input.hidden-input)
     -3:48.9.0 core:delete (input.hidden-input)
     -3:47 core:save (input.hidden-input)
 18x -3:28.6.0 core:undo (input.hidden-input)
 17x -3:24.2.0 core:redo (input.hidden-input)
     -0:40.4.0 core:copy (input.hidden-input)
     -0:30.1.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:28.6.0 core:paste (input.hidden-input)
     -0:27.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
Remote-FTP 1.1.3 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by icetee** [comment] 2017-09-29 11:48
Duplicate of #903

**Closed as completed by icetee** 2017-09-29 11:48 UTC
