### ISSUE TITLE
'Auto Upload on Save' not working

### ISSUE THREAD

**Issue by mosscla** [icetee/remote-ftp#686] opened 2017-02-09 20:24 UTC
Hello. Recently Auto upload on save is not working properly. I used to be able to open Atom, make changes to a file, save, and it would automatically upload. Now if I do that it does not upload. In order to get it to upload I have to manually connect first, then any future saves will be uploaded.

I did some debugging in remote-ftp.js and if I comment out the following line it uploads as intended, without me having to manually connect:
`if (self.client.ftpConfigPath !== self.client.getConfigPath()) return;`

I used console log and `self.client.ftpConfigPath` does return the correct path. If I try to console log `self.client.getConfigPath()` it returns undefined. Any help is greatly appreciated!

**Comment by samifouad** [comment] 2017-02-10 06:00
That's interesting, I'm fairly new to this plugin so I don't ever remember that being a feature in the versions I've used. I've always launched Atom and then pressed Connect before working. So to be clear, auto upload is working, auto connect on launch is not working, right?

**Comment by mosscla** [comment] 2017-02-15 17:49
That is correct. It used to auto-connect on first save.

**Comment by jpxd** [comment] 2017-02-21 11:32
@mosscla Do you have set the `multipleHostsEnabled` flag?

**Comment by icetee** [comment] 2017-12-03 22:27
I could not reproduce. I think you tried other project folders and this plugin no supported multi project yet. I close this issue.

The new version included status bar. It can be switched on/off.
![remote-statusbar](https://user-images.githubusercontent.com/1855340/33530553-6b32db48-d881-11e7-93e2-576dac4f86b2.JPG)

**Closed as completed by icetee** 2017-12-03 22:27 UTC
Labels: help wanted
