### ISSUE TITLE
Watch stop working in atom 1.14.3 ia32 version

### ISSUE THREAD

**Issue by querysol** [icetee/remote-ftp#708] opened 2017-02-22 11:11 UTC
After update watch stop working

**Comment by samifouad** [comment] 2017-02-22 14:50
What is your config setting for watch and what OS version are you on?

**Comment by samifouad** [comment] 2017-02-22 14:52
Going to close this as a dupe of #706 just to keep troubleshooting in one thread

**Closed as completed by samifouad** 2017-02-22 14:52 UTC
Labels: duplicate
