### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by kaihei777** [icetee/remote-ftp#1191] opened 2018-07-12 01:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.5
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/hoge/aaa.q'

```
At fs.js:904

Error: ENOTDIR: not a directory, scandir '/Users/hoge/aaa.q'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:580:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:137:27)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:741:24)
    at Client._next (/packages/remote-ftp/lib/client.js:643:39)
    at /packages/remote-ftp/lib/client.js:743:16
    at Object.e (/packages/remote-ftp/lib/connectors/sftp.js:610:22)
    at /packages/remote-ftp/lib/connectors/sftp.js:499:27)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:2923:5
    at cb (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:972:15)
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:387:17)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -2:28.5.0 core:paste (input.hidden-input)
     -2:28.2.0 core:save (input.hidden-input)
     -1:35.2.0 remote-ftp:connect (div.tool-panel.tree-view)
     -1:19.4.0 remote-ftp:upload-selected (span.name.icon.icon-file-text)
     -1:09.0 tabs:close-all-tabs (div.title)
     -0:56 remote-ftp:sync-with-local (li.file.entry.list-item.selected)
     -0:26.1.0 remote-ftp:connect (input.hidden-input)
     -0:21.9.0 remote-ftp:toggle (input.hidden-input)
     -0:10.4.0 core:move-down (input.hidden-input)
     -0:10.2.0 core:select-down (input.hidden-input)
     -0:10 core:cut (input.hidden-input)
     -0:09.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
editorconfig 2.2.2 
git-control 0.9.0 
git-history 3.3.0 
intentions 1.1.5 
japanese-menu 1.14.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-php 1.5.1 
linter-ruby 1.2.6 
linter-ui-default 1.7.1 
qolor 0.4.2 
react 0.18.0 
remote-ftp 2.2.0 
script 3.18.1 
```

**Comment by icetee** [comment] 2019-12-23 03:02
Duplicate of #1054

**Closed as completed by icetee** 2019-12-23 03:02 UTC
