### ISSUE TITLE
.*Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\W2\root\workspace\nodejs\basic_serv...

### ISSUE THREAD

**Issue by dongmin-2** [icetee/remote-ftp#1241] opened 2019-01-04 07:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\q\Desktop\W2\root\workspace\nodejs\basic_server\routes'

```
At C:\Users\q\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\q\Desktop\W2\root\workspace\nodejs\basic_server\routes'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
```

### Commands

```
  2x -5:43.5.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.project-root.expanded.selected)
     -5:08.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
  2x -5:03.7.0 core:backspace (input.hidden-input)
     -5:01.9.0 core:confirm (input.hidden-input)
     -4:55.4.0 remote-ftp:delete-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:52.1.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.collapsed.selected)
     -4:48.6.0 core:confirm (input.hidden-input)
     -4:39.7.0 core:save (input.hidden-input)
  2x -4:36.1.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.expanded.selected)
     -4:22.8.0 remote-ftp:delete-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:16 remote-ftp:add-folder (li.directory.entry.list-nested-item.collapsed.selected)
     -4:13.8.0 core:confirm (input.hidden-input)
     -4:08.2.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
     -4:03.9.0 core:confirm (input.hidden-input)
  2x -3:42.9.0 remote-ftp:delete-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:31.1.0 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.collapsed.selected)
```

### Non-Core Packages

```
remote-ftp 2.2.2 
```

**Comment by icetee** [comment] 2019-12-23 02:53
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:53 UTC
