### ISSUE TITLE
Missing first character of root folder

### ISSUE THREAD

**Issue by bay-lylekarstensen** [icetee/remote-ftp#1073] opened 2017-12-05 01:51 UTC
Using FTP mode when downloading a file to the local computer, remote-ftp plugin creates the folder structure based on the FTP directory structure of the file. The problem is that the first character of the root folder is missing.

Example:
If the server path is /development/somefile.txt

on the location computer you get
/evelopment/somefile.txt

**Comment by icetee** [comment] 2017-12-05 07:08
Duplicate of https://github.com/icetee/remote-ftp/issues/1051

**Closed as completed by icetee** 2017-12-05 07:08 UTC
