### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Desktop/Daily/Remote_CRM_Repos/Atom_Bat_CRM/...

### ISSUE THREAD

**Issue by Jalisinfo** [icetee/remote-ftp#1198] opened 2018-08-15 06:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/crm/Desktop/Daily/Remote_CRM_Repos/Atom_Bat_CRM/frontend/views/myinbox'

```
At fs.js:904

Error: ENOTDIR: not a directory, scandir '/Users/crm/Desktop/Daily/Remote_CRM_Repos/Atom_Bat_CRM/frontend/views/myinbox'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:580:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:137:27)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:965:32)
    at /packages/remote-ftp/lib/client.js:965:55
    at /packages/remote-ftp/lib/connectors/sftp.js:626:63)
    at /packages/remote-ftp/lib/connectors/sftp.js:629:46)
    at Object.e (/packages/remote-ftp/lib/connectors/sftp.js:649:28)
    at /packages/remote-ftp/lib/connectors/sftp.js:499:27)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:2923:5
    at cb (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:972:15)
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:387:17)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
atom-clock 0.1.16 
atom-css-class-checker 0.4.3 
atom-eclipse-syntax 0.0.6 
city-lights-syntax 1.1.8 
html-id-class-snippets 1.4.1 
improved-asp-html 1.13.1 
language-asp 1.1.1 
language-asp-core-2 0.1.1 
linter-write-good 0.9.0 
nord-atom-syntax 0.9.1 
qolor 0.4.2 
remote-ftp 2.2.0 
teletype 0.13.3 
zentabs 0.8.9 
```

**Comment by icetee** [comment] 2019-12-23 03:02
Duplicate of #1054

**Closed as completed by icetee** 2019-12-23 03:02 UTC
