### ISSUE TITLE
Connection successful, Listing hangs

### ISSUE THREAD

**Issue by iampatrick** [icetee/remote-ftp#1101] opened 2018-01-03 21:30 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

I've seen similar bugs but for different protocols and I have a console error which I haven't seen posted yet.

### Description

Can successfully connect via FTP but hangs indefinitely on "Listing".
There are no immediately visible notifications from Atom and the FTP responses look right. When I open the dev tools, the console has an error which appears to be the culprit.

The message is as follows:
Uncaught ReferenceError: reentry is not defined
    at C:\Users\Patrick\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:937
    at C:\Users\Patrick\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:962
(anonymous) @ C:\Users\Patrick\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:937
(anonymous) @ C:\Users\Patrick\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:962

### Steps to Reproduce

1. Attempt to connect. 
2. Successfully connect.
3. Progress bar with label "Listing" appears and doesn't go anywhere.

**Expected behavior:** Show listing of files in Remote panel upon successful connection. This worked up until recently.
**Actual behavior:** Hangs
**Reproduces how often:** 100% of FTP connections to my passive FTP server. Other SFTP connections work fine.

### Versions

Windows 10 Home x64
Atom 1.23.2 x64
remote-ftp 2.1.2

**Comment by icetee** [comment] 2018-01-05 23:56
Duplicate of #1078

**Closed as completed by icetee** 2018-01-05 23:56 UTC
