### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '$ATOM_HOME/packages\remote-ftp\admin_int\api-...

### ISSUE THREAD

**Issue by cebik16** [icetee/remote-ftp#1206] opened 2018-09-10 13:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\FlyGo\.atom\packages\remote-ftp\admin_int\api-flight2\app\Libraries\Suppliers\Pyton'

```
At C:\Users\FlyGo\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\FlyGo\.atom\packages\remote-ftp\admin_int\api-flight2\app\Libraries\Suppliers\Pyton'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:674:16)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/sftp.js:295:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -5:55.6.0 core:confirm (input.hidden-input)
     -5:47 remote-ftp:delete-selected (span.name.icon.default-icon)
     -5:43.1.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -5:39.1.0 core:cancel (input.hidden-input)
     -5:36.1.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
     -5:27.6.0 core:confirm (input.hidden-input)
     -5:22.8.0 remote-ftp:delete-selected (li.directory.entry.list-nested-item.collapsed.selected)
     -5:19 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
  2x -5:09.3.0 core:backspace (input.hidden-input)
     -5:08.0 core:confirm (input.hidden-input)
     -5:01.6.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
     -4:57.6.0 core:confirm (input.hidden-input)
     -4:47.5.0 core:select-all (input.hidden-input)
     -4:47.2.0 core:copy (input.hidden-input)
     -4:32.7.0 remote-ftp:permission-selected (li.directory.entry.list-nested-item.expanded.selected)
     -4:11 remote-ftp:refresh-selected (li.directory.entry.list-nested-item.expanded.selected)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.5.3 
atom-beautify 0.33.0 
atom-nodejs-snippets 2.1.1 
atom-typescript 12.6.3 
auto-detect-indentation 1.3.0 
autocomplete-angular-material 0.4.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.24 
fold-functions 0.5.0 
goto-definition 1.3.4 
laravel 0.7.1 
laravel-eloquent-snippets 2.0.0 
minimap 4.29.8 
platformio-ide-terminal 2.8.4 
remote-ftp 2.2.0 
tree-view-auto-collapse 1.0.2 
```

**Comment by icetee** [comment] 2019-12-23 02:52
Duplicate of #903

**Closed as completed by icetee** 2019-12-23 02:52 UTC
